CREATE USER 'barview'@'localhost';

GRANT USAGE ON * . * TO  'barview'@'localhost' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS  `barview` ;

GRANT ALL PRIVILEGES ON  `barview` . * TO  'barview'@'localhost';